name = "thaarakam"
compatibility_date = "2025-01-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "thaarakam-db"
database_id = "244387d1-3d22-40be-879b-93681f607432"
